config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'pages#home'

  get '/users/sign_out' => 'devise/sessions#destroy'

  get 'my_products', to: 'products#my_products'

  get '/bookings/:id/accept', to: 'bookings#accept', as: 'accept_booking'
  get '/bookings/:id/reject', to: 'bookings#reject', as: 'reject_booking'


  resources :products do
    resources :bookings, only: %i[new create destroy]

    collection do
      get :search
    end

    member do
      get :reviews
    end

    resources :bookings, only: [ :new, :create, :destroy ]
  end

  resources :bookings, except: [ :new, :index, :create ] do
    resources :reviews, only: [ :new, :create ]

  end

  resources :reviews, except: [ :new, :create ]

  get '/bookings', to: 'bookings#index'

  get '/error', to: 'errors#not_found'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_user
  before_action :set_booking, only: %i[new create]
  before_action :set_review, only: %i[show edit update destroy]

  def index
    reviews_all = policy_scope(Review)
    @reviews = reviews_all.select do |review|
      booking = Booking.find(review.booking_id)
      booking.user_id == @user.id
    end
  end

  def new
    @review = Review.new
    authorize @review
  end

  def create
    @review = Review.new(review_params)
    @review.booking_id = @booking.id
    authorize @review
    @review.save
    if @review.save
      redirect_to review_path(@review)
    else
      render :new
    end
  end

  def show
    authorize @review
  end

  def edit
    authorize @review
  end

  def update
    authorize @review
    @review.update(review_params)

    redirect_to review_path(@review)
  end

  def destroy
    @review.destroy
    redirect_to bookings_path
    authorize @review
  end

  private

  def set_user
    @user = current_user
  end

  def set_booking
    @booking = Booking.find(params[:booking_id])
  end

  def review_params
    params.require(:review).permit(:rating, :content)
  end

  def set_review
    @review = Review.find(params[:id])
  end
end

app/views/reviews/edit.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h1 class="display-1 pt-5">Mes avis</h1>
  </div>
</div>

<h1>Modifier votre avis</h1>
<div class="container">
  <%= simple_form_for [ @review ] do |f| %>
    <%= f.input :rating, collection: [1, 2, 3, 4, 5] %>
    <%= f.input :content, hint: "Modifiez votre commentaire pour cet avis" %>
    <%= f.submit "Modifier l'avis", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/index.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Mes avis</h2>
  </div>
</div>

<div class="container">
  <div class="row d-flex justify-content-center">
    <% @reviews.each do |review| %>
      <% @booking = Booking.find(review.booking_id) %>
      <% @product = Product.find(@booking.product_id) %>
      <div class="review-card col-4 shadow-sm m-2 border">
        <div>
          <% if @product.photo.key.nil? %>
            <%= image_tag "no-image.png", class:"img-fluid width: 100% height: auto" %>
          <% else %>
            <%= cl_image_tag @product.photo.key, class:"img-fluid width: 100% height: auto" %>
          <% end %>

          <div class="my-3 star-rating">
            <% if review.rating == 5 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i>
              </div>
            <% elsif review.rating == 4 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 3 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 2 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% elsif review.rating == 1 %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% else %>
              <div class="d-flex">
                <i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
              </div>
            <% end %>
          </div>

          <p><%= review.content %></p>

          <p>À partir de <strong><%= @booking.start_date %></strong> jusqu'au <strong><%= @booking.end_date %></strong></p>
          <p>Total price <strong><%= @booking.total_price %>€</strong></p>

          <div>
            <%= link_to "Voir", review_path(review), class: "text-success" %>
            <%= link_to "Éditer", edit_review_path(review), class: "text-warning" %>
            <%= link_to "Supprimer",
            review_path(review),
            method: :delete,
            data: { confirm: "Êtes-vous sûr?" }, class: "text-danger" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <%= link_to 'Réservations', bookings_path, class: "btn btn-primary" %>
</div>

app/views/reviews/new.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Ajouter un commentaire</h2>
  </div>
</div>

<% @product = Product.find(@booking.product_id) %>
<h1>Comment s'est passé votre location <strong class="text-muted"><%= @product.address %></strong>?</h1>
<div class="container">
  <%= simple_form_for [ @booking, @review ] do |f| %>
    <%= f.input :rating, collection: [1, 2, 3, 4, 5] %>
    <%= f.input :content, hint: "Parlez-nous de votre expérience avec #{@product.title}" %>
    <%= f.submit "Ajouter un commentaire", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/reviews/show.html.erb
<div class="cover mb-4 d-flex align-items-center justify-content-center">
  <div class="text-center text-white">
   <h2 class="display-1 pt-5">Commentaires</h2>
  </div>
</div>

<% @booking = Booking.find(@review.booking_id) %>
<% @product = Product.find(@booking.product_id) %>
<div class="container">
  <div class="d-flex justify-content-around align-items-center">
    <h1><strong class="text-muted"><%= @product.title %></strong></h1>
    <%= link_to "Retour sur votre reservation", booking_path(@booking), class: "btn btn-primary btn-sm" %>
  </div>
  <div class="review-card d-flex row justify-content-around">
    <div class="col-5">
      <% if @product.photo.key.nil? %>
        <%= image_tag "no-image.png", class:"review-image" %>
      <% else %>
        <%= cl_image_tag @product.photo.key, class:"review-image" %>
      <% end %>
    </div>
    <div class="col-5">
      <div class="star-rating my-3">
        <p>Rating:</p>
        <% if @review.rating == 5 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i>
          </div>
        <% elsif @review.rating == 4 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% elsif @review.rating == 3 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% elsif @review.rating == 2 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% elsif @review.rating == 1 %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: gold"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% else %>
          <div class="d-flex">
            <i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i><i class="fas fa-star" style="color: grey"></i>
          </div>
        <% end %>
      </div>
      <p><strong>Comentaire: </strong><%= @review.content %></p>
      <p><strong>Adresse: </strong><%= @product.address %></p>
      <p><strong>À partir de: </strong><%= @booking.start_date %><strong> jusq'au </strong><%= @booking.end_date %></p>
      <p><strong>Total price: </strong><%= @booking.total_price %>€</p>

      <div>
        <%= link_to "Modifier", edit_review_path(@review), class: "btn btn-primary btn-sm" %>
        <%= link_to "Suprimer",
        review_path(@review),
        method: :delete,
        data: { confirm: "Êtes-vous sûr?" }, class: "btn btn-primary btn-sm" %>
      </div>
    </div>
  </div>
</div>